services:
  - type: web
    name: playbeat-backend
    runtime: node
    region: oregon
    plan: standard
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        scope: run
      - key: JWT_SECRET
        scope: run
      - key: NODE_ENV
        value: production
        scope: run
      - key: STRIPE_ACCOUNT_ID
        scope: run
      - key: STRIPE_PUBLISHABLE_KEY
        scope: run
      - key: STRIPE_SECRET_KEY
        scope: run
      - key: STRIPE_RESTRICTED_KEY
        scope: run
      - key: FRONTEND_URL
        scope: run
      - key: PORT
        value: "3000"
        scope: run
